require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DisputesController do
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DisputesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all disputes as @disputes" do
      dispute = Factory :dispute
      get :index, {}, valid_session
      assigns(:disputes).should eq([dispute])
    end
  end

  describe "GET show" do
    it "assigns the requested dispute as @dispute" do
      dispute = Factory :dispute
      get :show, {:id => dispute.to_param}, valid_session
      assigns(:dispute).should eq(dispute)
    end
  end

  describe "GET new" do
    it "assigns a new dispute as @dispute" do
      get :new, {}, valid_session
      assigns(:dispute).should be_a_new(Dispute)
    end
  end

  describe "GET edit" do
    it "assigns the requested dispute as @dispute" do
      dispute = Factory :dispute
      get :edit, {:id => dispute.to_param}, valid_session
      assigns(:dispute).should eq(dispute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      let(:dispute_params) { Factory.attributes_for(:dispute).merge(:company_attributes => Factory.attributes_for(:company)) }

      it "creates a new Dispute" do
        expect {
          post :create, {:dispute => dispute_params}, valid_session
        }.to change(Dispute, :count).by(1)
      end

      it "assigns a newly created dispute as @dispute" do
        post :create, {:dispute => dispute_params}, valid_session
        assigns(:dispute).should be_a(Dispute)
        assigns(:dispute).should be_persisted
      end

      it "redirects to the created dispute" do
        post :create, {:dispute => dispute_params}, valid_session
        response.should redirect_to(Dispute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dispute as @dispute" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dispute.any_instance.stub(:save).and_return(false)
        post :create, {:dispute => {}}, valid_session
        assigns(:dispute).should be_a_new(Dispute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dispute.any_instance.stub(:save).and_return(false)
        post :create, {:dispute => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dispute" do
        dispute = Factory :dispute
        # Assuming there are no other disputes in the database, this
        # specifies that the Dispute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dispute.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dispute.to_param, :dispute => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dispute as @dispute" do
        dispute = Factory :dispute
        put :update, {:id => dispute.to_param, :dispute => Factory.attributes_for(:dispute)}, valid_session
        assigns(:dispute).should eq(dispute)
      end

      it "redirects to the dispute" do
        dispute = Factory :dispute
        put :update, {:id => dispute.to_param, :dispute => Factory.attributes_for(:dispute)}, valid_session
        response.should redirect_to(dispute)
      end
    end

    describe "with invalid params" do
      it "assigns the dispute as @dispute" do
        dispute = Factory :dispute
        # Trigger the behavior that occurs when invalid params are submitted
        Dispute.any_instance.stub(:save).and_return(false)
        put :update, {:id => dispute.to_param, :dispute => {}}, valid_session
        assigns(:dispute).should eq(dispute)
      end

      it "re-renders the 'edit' template" do
        dispute = Factory :dispute
        # Trigger the behavior that occurs when invalid params are submitted
        Dispute.any_instance.stub(:save).and_return(false)
        put :update, {:id => dispute.to_param, :dispute => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dispute" do
      dispute = Factory :dispute
      expect {
        delete :destroy, {:id => dispute.to_param}, valid_session
      }.to change(Dispute, :count).by(-1)
    end

    it "redirects to the disputes list" do
      dispute = Factory :dispute
      delete :destroy, {:id => dispute.to_param}, valid_session
      response.should redirect_to(disputes_url)
    end
  end

end
